name: git_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI e Animações
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1

  # Gerenciamento de Estado
  provider: ^6.1.5
  flutter_riverpod: ^2.6.1

  # Persistência de Dados
  shared_preferences: ^2.5.3
  hive_flutter: ^1.1.0

  # Permissões e Arquivos
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  camera: ^0.11.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5

  # Notificações e Requisições
  another_flushbar: ^1.12.30
  http: ^1.4.0
  objectbox: ^4.3.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  analyzer: ^6.5.0
  hive: ^2.0.5
  hive_generator: ^2.0.1 
  build_runner: ^2.4.4
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.5
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    