// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCptCz8VSK1p71GZIb4eR-20Mdzu_vnqPE',
    appId: '1:63294384473:web:c7a608151895d27fdb4448',
    messagingSenderId: '63294384473',
    projectId: 'fir-notifications-84504',
    authDomain: 'fir-notifications-84504.firebaseapp.com',
    storageBucket: 'fir-notifications-84504.firebasestorage.app',
    measurementId: 'G-P9BXPT1GB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzTNlZeK3BIo5wvqDh5Dm97_36OJHgOFk',
    appId: '1:63294384473:android:ae172faeca68135adb4448',
    messagingSenderId: '63294384473',
    projectId: 'fir-notifications-84504',
    storageBucket: 'fir-notifications-84504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvecf3MFDqSW-Pel5P9J8Ay57_XfAIZ5Q',
    appId: '1:63294384473:ios:feabaaa23dae2164db4448',
    messagingSenderId: '63294384473',
    projectId: 'fir-notifications-84504',
    storageBucket: 'fir-notifications-84504.firebasestorage.app',
    iosBundleId: 'com.example.gitApp',
  );

}